ACCOUNT_COLUMNS:
- reqid
- account
- key
- value
- currency
ACCOUNT_INFO_SHOW_LIST:
- UnrealizedPnL
- RealizedPnL
- NetLiquidation
- TotalCashValue
- BuyingPower
- GrossPositionValue
- AvailableFunds
ASSET_LIST:
- TSLA
- AAPL
- NVDA
- META
- AMD
- AMZN
- GOOG
- IBM
- JPM
- KO
- COIN
AXIS_WIDTH: 1
BAR_WIDTH: 0.3
BUY_LMT_PLUS: 0.05
CANDLE_WIDTH: 0.3
DEFAULT_ASSET: TSLA
DEFAULT_CHART_INTERVAL: 1 Minite
DEFAULT_Y_MARGIN: 3
DOWN_COLOR: r
MAX_NUM_CANDLE: 300
MIN_BAR_COUNT: 100
NORMAL_FONT: Arial
PEN_WIDTH: 1
PORTFOLIO_COLUMNS:
- symbol
- sectype
- exchange
- position
- marketprice
- marketvalue
- averagecost
- unrealizedpnl
- realizedpnl
SELL_LMT_PLUS: -0.05
UP_COLOR: g
__version__: '1.0'
database.database: database.db
database.host: ''
database.name: sqlite
database.password: ''
database.port: 0
database.timezone: Europe/London
database.user: ''
datafeed.name: data.yfdatafeed
datafeed.password: ''
datafeed.username: ''
email.password: ''
email.port: 465
email.receiver: ''
email.sender: ''
email.server: smtp.eagloo.co.uk
email.username: ''
font.family: Arial
font.size: 12
log.active: true
log.console: true
log.file: true
log.level: 20
palette: dark
