__version__: '1.0'
database.database: database.db
database.host: ''
database.name: sqlite
database.password: ''
database.port: 0
database.user: ''
datafeed.name: ''
datafeed.password: ''
datafeed.username: ''
email.password: ''
email.port: 465
email.receiver: ''
email.sender: ''
email.server: smtp.eagloo.co.uk
email.username: ''
font.family: Arial
font.size: 12
log.active: true
log.console: true
log.file: true
log.level: 50
palette: dark
